# Generated by Django 3.1.6 on 2021-02-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_auto_20210212_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifications',
            name='version',
            field=models.CharField(max_length=10),
        ),
    ]
