# Generated by Django 3.1.6 on 2021-03-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_auto_20210213_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='specifications',
            name='text_json',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='info_person',
        ),
    ]
